env:
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CACHE_DIR: "/cache/cardano-wallet"
  LC_ALL: "en_US.UTF-8"
  TESTS_LOGDIR: "/tmp/wallet-integration-logs"
  TESTS_RETRY_FAILED: "yes"

steps:
  - label: 'Prevent merging to wrong branch'
    if: 'build.branch == "bors/staging"'
    command: './.buildkite/check-bors.sh'
    agents:
      system: x86_64-linux
  - wait: ~
    if: 'build.branch == "bors/staging"'

  - label: 'Stack Rebuild'
    command:
      - "rm -rf $TESTS_LOGDIR && mkdir $TESTS_LOGDIR"
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    timeout_in_minutes: 120
    artifact_paths:
      - "/build/cardano-wallet/.stack-work/logs/cardano-wallet*.log"
      - "/tmp/wallet-integration-logs/*/*.log"
    agents:
      system: x86_64-linux

  - label: 'Check Cabal Configure (Haskell.nix shellFor)'
    command:
      - 'nix-shell --run "cabal update"'
      - 'nix-shell --run "cabal configure --project-file=cabal-nix.project --enable-tests --enable-benchmarks"'
      - 'nix-shell --run "cabal configure --project-file=cabal-nix.project -frelease --enable-tests --enable-benchmarks"'
    agents:
      system: x86_64-linux

  - label: 'Check Cabal Configure'
    command: 'nix-shell nix/cabal-shell.nix --run "scripts/buildkite/cabal-ci.sh configure"'
    agents:
      system: x86_64-linux

  - label: 'Check auto-generated Nix'
    commands:
      - './nix/regenerate.sh --cache /dev/null'
      - 'nix-build ./nix -A iohkNix.checkStackProject -o check-stack-project.sh && ./check-stack-project.sh'
    agents:
      system: x86_64-linux

  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run .buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux

  - label: 'HLint'
    command: 'nix-shell --run "hlint lib"'
    agents:
      system: x86_64-linux

  - label: 'Validate OpenAPI Specification'
    command: 'nix-shell --run "openapi-spec-validator --schema 3.0.0 specifications/api/swagger.yaml"'
    agents:
      system: x86_64-linux

  - label: 'Docker Image'
    command:
      - "nix-build .buildkite/docker-build-push.nix --argstr dockerHubRepoName inputoutput/cardano-wallet -o docker-build-push"
      - "./docker-build-push"
    agents:
      system: x86_64-linux
    soft_fail:
      - exit_status: '*'

  - label: 'TODO list'
    command: 'nix-shell --run scripts/todo-list.sh'
    agents:
      system: x86_64-linux

  - label: 'Lint bash shell scripts'
    command: './scripts/shellcheck.sh'
    agents:
      system: x86_64-linux
